# -*- coding: utf-8 -*-
"""calculate_log_return_and_standard_dev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w05w27Upctu4yGzaXTfzmJuNrTq6-nug
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
# %matplotlib inline

energy_stock_data_df_close_price_only = pd.read_csv('/Users/paul/a_MSDS460_jupyter/group_assignment_2_stocks/data/energy_stock_data_close_price_only_1999_to_2024.csv')

energy_stock_data_df_close_price_only.head()

energy_stock_data_df_close_price_only['Date'] = pd.to_datetime(energy_stock_data_df_close_price_only['Date'])
energy_stock_data_df_close_price_only.set_index('Date', inplace=True)

log_returns = 100*np.log(energy_stock_data_df_close_price_only / energy_stock_data_df_close_price_only.shift(1))
mean_log_returns = log_returns.mean()
std_dev_log_returns = log_returns.std()

log_returns.head()

mean_log_returns

std_dev_log_returns