# -*- coding: utf-8 -*-
"""download_tickers_separately.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IiYDusXt-z4uxAMC4xPd0Y0LnZQFDQ1Z
"""

# this code downloads each ticker into a df separately and reformats that df to the same format as the example in  https://github.com/bryancwh/algo-trading-mean-reversion/blob/main/Mean%20Reversion.ipynb
# saves off each df as a csv into the monte_carlo_data/each_ticker_as_a_separate_csv folder


import yfinance as yf
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

# testing with one tixker

# tickers_with_all_data = ["XOM"]

tickers_with_all_data = ["XOM", "CVX", "COP", "EOG", "EPD", "WMB", "OKE", "LNG", "OXY", "HES"]

# https://stackoverflow.com/questions/79291334/drop-the-ticker-row-of-yfinance-dataframe

# xom_test = yf.download("XOM", start="1999-01-01", end = "2024-01-01", multi_level_index = False)

# xom_test.head()

# xom_test.reset_index(inplace=True)
# xom_test.head()

# xom_test = xom_test.rename(columns={
#     'Date': 'date',
#     'Open': 'open',
#     'High': 'high',
#     'Low': 'low',
#     'Close': 'close',
#     'Volume': 'volume'
# })
# xom_test.head()

# !ls '/content/drive/MyDrive/shared_folders/MSDS 460/Monte Carlo/monte_carlo_data/each_ticker_as_a_separate_csv'

stock_dfs = {}

for ticker in tickers_with_all_data:
    df = yf.download(ticker, start="1999-01-01", end = "2024-01-01", multi_level_index = False)

    df.reset_index(inplace=True)

    df = df.rename(columns={
        'Date': 'date',
        'Open': 'open',
        'High': 'high',
        'Low': 'low',
        'Close': 'close',
        'Volume': 'volume'
    })

    df['date'] = pd.to_datetime(df['date'])

    stock_dfs[ticker] = df

    df.to_csv(f'/content/drive/MyDrive/shared_folders/MSDS 460/Monte Carlo/monte_carlo_data/each_ticker_as_a_separate_csv/{ticker}_data.csv', index=False)

cop_df = stock_dfs["XOM"]
print(cop_df.head())



