# -*- coding: utf-8 -*-
"""download_energy_stock_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGQKcSD9PjbWwFzIRAE8qermnSxtz0lL
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
# %matplotlib inline

# top energy companies
# https://finance.yahoo.com/research-hub/screener/sec-ind_sec-largest-equities_energy/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAFGOMEvqsP_FnUmK2iPP7vn-0aCJZ6N7p8n3R_NDFTquke4DEz9ApRfhKGK4ECyuxHuZxsNfV53FuEMCTeZ_RvI06GAuFLXgefyx0UUdlAPkrJ978RmvqXT0r8nfSvCWPTfHsNNSXM2o_GUmNRlvITdoo5UWvfB1cnwKb3PVuCQC

tickers = [
    "XOM", "CVX", "COP", "EOG", "EPD", "WMB", "KMI", "OKE", "MPLX", "PSX", "LNG", "MPC", "OXY", "HES", "FANG"

]

energy_stock_data_df = yf.download(tickers, start="1999-01-01", end = "2024-01-01")

energy_stock_data_df.head()

energy_stock_data_df.columns

# KMI, MPC, MPLX, PSX, FANG are all missing data.

energy_stock_data_df.info()

# neck down to ten stocks by removing stovks that are missing data

tickers_with_all_data = ["XOM", "CVX", "COP", "EOG", "EPD", "WMB", "OKE", "LNG", "OXY", "HES"]

energy_stock_data_df_10_all_data = yf.download(tickers_with_all_data, start="1999-01-01", end = "2024-01-01")

energy_stock_data_df_10_all_data.head()

energy_stock_data_df_10_all_data.info()

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive/Colab Notebooks/MSDS460_LP/group_assignment_2_stock_mote_carlo"

energy_stock_data_df_10_all_data.to_csv('/content/drive/My Drive/Colab Notebooks/MSDS460_LP/group_assignment_2_stock_mote_carlo/data/energy_stock_data_all_1999_to_2024.csv', index=True)

energy_stock_data_df_close_price_only = energy_stock_data_df_10_all_data['Close']

energy_stock_data_df_close_price_only.to_csv('/content/drive/My Drive/Colab Notebooks/MSDS460_LP/group_assignment_2_stock_mote_carlo/data/energy_stock_data_close_price_only_1999_to_2024.csv', index=True)